[project]
name = "hdf5"
version = "1.14.5"
description = "A pixi project for deveolping the windows variant of hdf5 compiled with fortran"
channels = ["conda-forge"]
platforms = ["win-64"]

[environments]
flang = ["flang"]
ifx = ["ifx"]

[dependencies]
cmake = "*"
ninja = "*"
openssl = "*"
zlib = "*"
libaec = "*"
libcurl = "*"
vswhere = "*"

[feature.flang.dependencies]
flang = "19*"
clang = "*"
clangxx = "*"

[feature.flang.tasks]
build = { cmd = ["cmake", "-DCMAKE_BUILD_TYPE=Release", "--preset", "msvc-flang", "-B", "build/msvc-flang", "--fresh"], description = "Build the project" }
install = { cmd = ["ninja", "-C", "build/msvc-flang", "install"], description = "Install the project" }
test_flang = { cmd = ["flang_checks/run.bat"], description = "Run the tests" }

[feature.ifx.tasks]
build_intel = { cmd = ["cmake", "-DCMAKE_BUILD_TYPE=Release", "--preset", "msvc-ifx", "-B", "build/msvc-ifx", "--fresh"], description = "Build the project", env = { ACTIVATE_INTEL = "1" } }
test_intel = { cmd = ["where", "ifx.exe"], description = "Build the project" }
[feature.ifx.target.win-64.activation]
scripts = ["activate_intel.bat"]

[target.win-64.activation]
scripts = ["activate.bat"]