[project]
name = "hdf5"
version = "1.14.5"
description = "A pixi project for deveolping the windows variant of hdf5 compiled with fortran"
channels = ["conda-forge"]
platforms = ["win-64"]

[environments]
flang = ["flang"]
ifx = ["ifx"]
m2w64 = ["m2w64"]

[dependencies]
cmake = "*"
ninja = "*"
openssl = "*"
zlib = "*"
libaec = "*"
libcurl = "*"
vswhere = "*"

[feature.flang.dependencies]
flang = "19*"
clang = "*"
clangxx = "*"

[feature.m2w64.dependencies]
m2w64-sysroot_win-64 = "*"
gcc_win-64 = "13*"
gxx_win-64 = "13*"
gfortran_win-64 = "13*"
ld_impl_win-64 = "*"

[feature.m2w64.tasks]
cleanm2 = { cmd = ["rm", "-rf", "build/msvc-m2w64"], description = "Clean the project" }
buildm2 = { cmd = ["cmake", "-DCMAKE_EXE_LINKER_FLAGS=-lwinpthread", "-DCMAKE_BUILD_TYPE=Release", "--preset", "msvc-m2w64", "-B", "build/msvc-m2w64", "--fresh"], description = "Build the project", depends-on=["cleanm2"] }
installm2 = { cmd = ["ninja", "-C", "build/msvc-m2w64", "install"], description = "Install the project" }

[feature.flang.tasks]
build = { cmd = ["cmake", "-DCMAKE_BUILD_TYPE=Release", "--preset", "msvc-flang", "-B", "build/msvc-flang", "--fresh"], description = "Build the project" }
install = { cmd = ["ninja", "-C", "build/msvc-flang", "install"], description = "Install the project" }
test_flang = { cmd = ["flang_checks/run.bat"], description = "Run the tests" }
[feature.flang.target.win-64.activation]
scripts = ["activate.bat"]

[feature.ifx.tasks]
build_intel = { cmd = ["cmake", "-DCMAKE_BUILD_TYPE=Release", "--preset", "msvc-ifx", "-B", "build/msvc-ifx", "--fresh"], description = "Build the project", env = { ACTIVATE_INTEL = "1" } }
test_intel = { cmd = ["where", "ifx.exe"], description = "Build the project" }
[feature.ifx.target.win-64.activation]
scripts = ["activate.bat", "activate_intel.bat"]